IndexStore: repair Windows build
apple/swift-clang pull request #209
Opened 2018-09-17 18:22 UTC by compnerd

Building IndexStore would fail as `dllimport` would be applied to a non-inlined
function definition which is not permitted.  Remove the declaration to change
the error to a warning (inconsistent dll storage).  This allows us to build
correctly.  We could always apply the `dllexport` attribute to the definitions
to avoid the warning.

2018-09-17 18:22 UTC, compnerd commented
CC: @jrose-apple @akyrtzi

2018-09-17 18:53 UTC, akyrtzi requested changes
Ah that was my bad, thanks for addressing this!
But I'm not a huge fan of the rest of the whitespace changes, could you just remove the 'INDEXSTORE_PUBLIC' identifiers so we can have a commit that only does one thing (remove 'INDEXSTORE_PUBLIC' to fix the windows build) ?

2018-09-18 00:02 UTC, compnerd commented
@akyrtzi - sure ... though the whitespace changes are clang-format :-)

2018-09-18 00:26 UTC, akyrtzi approved these changes

2018-09-18 02:04 UTC, akyrtzi commented
To clarify, with "I'm not a huge fan of the rest of the whitespace changes" I did not mean that I don't like the formatting changes themselves, what I don't like is adding unrelated whitespace changes to your fix.

2018-09-18 16:06 UTC, merged

2018-09-18 16:07 UTC, compnerd commented
@jrose-apple, @tkremenek - whats the best way to get this cherry-picked to stable?

2018-09-18 16:24 UTC, bob-wilson commented
Create a PR for the swift-5.0-branch to cherry-pick it