[DirectoryWatcher] Fix cross-compilation checking fs_event availability.
apple/swift-clang pull request #361
Opened 2019-10-03 18:54 UTC by dcci

Some platforms have the header but don't have support for fs_event.

2019-10-03 18:54 UTC, dcci commented
@swift-ci test

2019-10-03 19:30 UTC, akyrtzi requested changes

2019-10-03 19:30 UTC, akyrtzi commented on lib/DirectoryWatcher/CMakeLists.txt
> +CHECK_SYMBOL_EXISTS("FSEventStreamRef" "CoreServices/CoreServices.h" HAS_FS_EVENTS)
In llvm it is called with the lowercased version, `check_symbol_exists`.
Also the macro will not be automatically be defined, you need to add a `#cmakedefine` in `include/clang/Config/config.h.cmake`.

For an example see how `HAVE_DLOPEN` is checked and defined in the llvm repo.

2019-10-05 00:37 UTC, dcci commented
Followed up in person with Argyrios and decided it's simpler to check the platform instead [at least here, maybe we'll do something different upstream]

2019-10-05 00:37 UTC, jkorous-apple approved these changes
LGTM

2019-10-05 00:37 UTC, dcci commented
@swift-ci test

2019-10-05 00:37 UTC, dcci commented
@swift-ci test

2019-10-07 05:11 UTC, merged